---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ xui_dir }}/db"
    - "{{ xui_dir }}/haproxy"

- name: Deploy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ xui_dir }}/haproxy/haproxy.cfg"
  notify: restart haproxy

- name: Run xui
  community.docker.docker_container:
    name: xui
    image: "{{ xui_image }}"
    pull: true
    volumes:
      - "{{ xui_dir }}/db:/etc/x-ui"
      - "/etc/letsencrypt:/root/cert:ro"
    env:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "false"
    network_mode: host
    restart_policy: unless-stopped
    tty: true

- name: Run haproxy
  community.docker.docker_container:
    name: haproxy
    image: "{{ haproxy_image }}"
    pull: true
    volumes:
      - "{{ xui_dir }}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
    network_mode: host
    restart_policy: unless-stopped
