---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Deploy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    validate: haproxy -c -f %s
  notify: Restart haproxy service

- name: Ensure HAProxy is running
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true

- name: Ensure curl present
  ansible.builtin.package:
    name: curl
    state: present

- name: Install x-ui via script
  ansible.builtin.shell: |
    {{ xui_control_install_cmd }}
  args:
    executable: /bin/bash
    creates: /usr/local/x-ui
  changed_when: true
  notify: Restart haproxy service
  