---
- name: Issue wildcard certificate
  ansible.builtin.include_tasks: deploy_cert.yml
  when: xui_control_deploy_cert | default(false) | bool

- name: Install 3x-ui
  ansible.builtin.include_tasks: install_3xui.yml
  when: xui_control_install_3xui | default(false) | bool

- name: Restore database from R2
  ansible.builtin.include_tasks: restore_db.yml
  when: xui_control_restore_db | default(false) | bool

- name: Add backup service
  ansible.builtin.include_tasks: add_backup_service.yml
  when: xui_control_add_backup_service | default(false) | bool
