---
- name: Deploy to new VPS
  hosts: xui_server
  become: true
  gather_facts: true
  roles:
    - role: xui_control
      vars:
        xui_control_deploy_cert: false
        xui_control_restore_db: true
        xui_control_install_3xui: true
        xui_control_add_backup_service: true
